### ISSUE TITLE
Implement connection options, inc load balancing

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseQuery#26]
Right now the main wiki database connection is fed to QueryEngine. Before deploying, we'll want to make it possible to run queries against a db other than the main wiki db.

One question here is if we want to use master and slave wiki dbs, or if it makes more sense to use one or more dedicated databases for QueryEngine. That the later is possible is probably not known by the relevant ops people yet.

**Comment by frimelle** [comment]
The task on Phabricator: https://phabricator.wikimedia.org/T87743
